version: "3.8"

services:
  gfb-lunch-order:
    image: ghcr.io/sebastiansucker/kantinen-kobold:latest
    build: .
    container_name: gfb-lunch-order
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data
    # Zeitzone wichtig, damit der Cron-Job zur richtigen Uhrzeit läuft
    environment:
      - TZ=Europe/Berlin
